/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tf_pc;

import Objetos.Grafo;
import Objetos.ProgramadorHorarios;

/**
 *
 * @author Dayana
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Grafo grafoPrincipal;
    public Principal() {
        initComponents();
        grafoPrincipal = new Grafo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        aulasPanel = new javax.swing.JPanel();
        datosAulasComboBox = new javax.swing.JComboBox<>();
        nombreAulaLabel = new javax.swing.JLabel();
        nombreAulaTextArea = new javax.swing.JTextField();
        eliminaraAulaButton = new javax.swing.JButton();
        registrarAulaButton = new javax.swing.JLabel();
        nombreRegistroAulaLabel = new javax.swing.JLabel();
        nombreRegistroAulaTextArea = new javax.swing.JTextField();
        capacidadRegistroAulaLabel = new javax.swing.JLabel();
        capacidadRegistroAulaTextArea = new javax.swing.JTextField();
        registroAulaButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        eliminaraAulaButton1 = new javax.swing.JButton();
        eliminaraAulaButton2 = new javax.swing.JButton();
        nombreAulaLabel1 = new javax.swing.JLabel();
        nombreAulaTextArea1 = new javax.swing.JTextField();
        capacidadRegistroAulaLabel1 = new javax.swing.JLabel();
        capacidadRegistroAulaTextArea1 = new javax.swing.JTextField();
        capacidadRegistroAulaLabel2 = new javax.swing.JLabel();
        capacidadRegistroAulaTextArea2 = new javax.swing.JTextField();
        profesoresPanel = new javax.swing.JPanel();
        datosProfesoresComboBox = new javax.swing.JComboBox<>();
        nombreProfesorLabel = new javax.swing.JLabel();
        códigoProfesorLabel = new javax.swing.JLabel();
        editarProfesorButton = new javax.swing.JButton();
        eliminarProfesorButton = new javax.swing.JButton();
        asignarCursosLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregarCursoProfesorButton = new javax.swing.JButton();
        eliminiarCursoProfesorButton = new javax.swing.JButton();
        codCursoTextArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        registrarProfesorButton = new javax.swing.JButton();
        nombreProfesorTextArea = new javax.swing.JTextField();
        codigoProfesorTextArea = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jSeparator3 = new javax.swing.JSeparator();
        jSpinner1 = new javax.swing.JSpinner();
        editarProfesorButton1 = new javax.swing.JButton();
        jSpinner2 = new javax.swing.JSpinner();
        nombreProfesorLabel1 = new javax.swing.JLabel();
        nombreProfesorTextArea1 = new javax.swing.JTextField();
        códigoProfesorLabel1 = new javax.swing.JLabel();
        codigoProfesorTextArea1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        jSpinner4 = new javax.swing.JSpinner();
        horariosPanel = new javax.swing.JPanel();
        GenerarHorarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        aulasPanel.setPreferredSize(new java.awt.Dimension(314, 483));

        datosAulasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aula1", "Aula2", "Aula3" }));

        nombreAulaLabel.setText("Nombre");

        eliminaraAulaButton.setText("Eliminar");

        registrarAulaButton.setText("Registrar Aula");

        nombreRegistroAulaLabel.setText("Nombre");

        capacidadRegistroAulaLabel.setText("Curso");

        registroAulaButton.setText("Registrar");
        registroAulaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAulaButtonActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        eliminaraAulaButton1.setText("Editar");
        eliminaraAulaButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaraAulaButton1ActionPerformed(evt);
            }
        });

        eliminaraAulaButton2.setText("Guardar");
        eliminaraAulaButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminaraAulaButton2ActionPerformed(evt);
            }
        });

        nombreAulaLabel1.setText("Curso");

        capacidadRegistroAulaLabel1.setText("Codigo");

        capacidadRegistroAulaLabel2.setText("Codigo");

        javax.swing.GroupLayout aulasPanelLayout = new javax.swing.GroupLayout(aulasPanel);
        aulasPanel.setLayout(aulasPanelLayout);
        aulasPanelLayout.setHorizontalGroup(
            aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aulasPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datosAulasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aulasPanelLayout.createSequentialGroup()
                        .addComponent(eliminaraAulaButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminaraAulaButton1)
                        .addGap(41, 41, 41)
                        .addComponent(eliminaraAulaButton))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreAulaLabel)
                            .addComponent(nombreAulaLabel1)
                            .addComponent(capacidadRegistroAulaLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capacidadRegistroAulaTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nombreAulaTextArea1)
                                .addComponent(nombreAulaTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))))
                .addGap(48, 48, 48)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registrarAulaButton)
                            .addGroup(aulasPanelLayout.createSequentialGroup()
                                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreRegistroAulaLabel)
                                    .addComponent(capacidadRegistroAulaLabel)
                                    .addComponent(capacidadRegistroAulaLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(capacidadRegistroAulaTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreRegistroAulaTextArea, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(capacidadRegistroAulaTextArea)))))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(registroAulaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        aulasPanelLayout.setVerticalGroup(
            aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aulasPanelLayout.createSequentialGroup()
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(registrarAulaButton)
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreRegistroAulaLabel)
                            .addComponent(nombreRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadRegistroAulaLabel)
                            .addComponent(capacidadRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadRegistroAulaLabel1)
                            .addComponent(capacidadRegistroAulaTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(registroAulaButton))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(datosAulasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAulaLabel)
                            .addComponent(nombreAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAulaLabel1)
                            .addComponent(nombreAulaTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadRegistroAulaLabel2)
                            .addComponent(capacidadRegistroAulaTextArea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminaraAulaButton)
                            .addComponent(eliminaraAulaButton1)
                            .addComponent(eliminaraAulaButton2)))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Aulas", aulasPanel);

        datosProfesoresComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prof 1", "Prof 2", "Prof 3", "Prof 4" }));

        nombreProfesorLabel.setText("Nombre");

        códigoProfesorLabel.setText("Código");

        editarProfesorButton.setText("Editar");

        eliminarProfesorButton.setText("Eliminar");

        asignarCursosLabel.setText("Asignar cursos al profesor");

        jLabel4.setText("Codigo Aula");

        agregarCursoProfesorButton.setText("Agregar");

        eliminiarCursoProfesorButton.setText("Eliminar");

        jLabel5.setText("Registrar Profesor");

        registrarProfesorButton.setText("Registrar");
        registrarProfesorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarProfesorButtonActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane12.setViewportView(jTextArea2);

        jLabel11.setText("Turno");

        jLabel14.setText("Hora inicio");

        jLabel15.setText("Bloques disponibles");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mañana", "tarde", "noche" }));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        editarProfesorButton1.setText("Guardar");

        nombreProfesorLabel1.setText("Nombre");

        códigoProfesorLabel1.setText("Código");

        jLabel16.setText("Turno");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mañana", "tarde", "noche" }));

        jLabel17.setText("Hora inicio");

        jLabel18.setText("Bloques disponibles");

        javax.swing.GroupLayout profesoresPanelLayout = new javax.swing.GroupLayout(profesoresPanel);
        profesoresPanel.setLayout(profesoresPanelLayout);
        profesoresPanelLayout.setHorizontalGroup(
            profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profesoresPanelLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(agregarCursoProfesorButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminiarCursoProfesorButton)
                                .addGap(72, 72, 72))
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addComponent(datosProfesoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(codCursoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                        .addGap(67, 67, 67)
                        .addComponent(jLabel5)
                        .addGap(255, 255, 255))
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(editarProfesorButton1)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel11)
                                            .addComponent(códigoProfesorLabel)
                                            .addComponent(nombreProfesorLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nombreProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codigoProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                                .addComponent(editarProfesorButton)
                                                .addGap(32, 32, 32)
                                                .addComponent(eliminarProfesorButton))
                                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(asignarCursosLabel))
                                .addGap(29, 29, 29)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(códigoProfesorLabel1)
                                    .addComponent(nombreProfesorLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreProfesorTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigoProfesorTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(registrarProfesorButton)))
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        profesoresPanelLayout.setVerticalGroup(
            profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datosProfesoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreProfesorLabel))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(códigoProfesorLabel)
                                    .addComponent(codigoProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(editarProfesorButton)
                                    .addComponent(eliminarProfesorButton)
                                    .addComponent(editarProfesorButton1))
                                .addGap(27, 27, 27)
                                .addComponent(asignarCursosLabel))
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreProfesorTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreProfesorLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(códigoProfesorLabel1)
                                    .addComponent(codigoProfesorTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jSpinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(registrarProfesorButton))))
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3)))
                .addGap(13, 13, 13)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codCursoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCursoProfesorButton)
                    .addComponent(eliminiarCursoProfesorButton))
                .addGap(177, 177, 177))
        );

        jTabbedPane2.addTab("Profesores", profesoresPanel);

        GenerarHorarios.setText("Generar Horario");
        GenerarHorarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarHorariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout horariosPanelLayout = new javax.swing.GroupLayout(horariosPanel);
        horariosPanel.setLayout(horariosPanelLayout);
        horariosPanelLayout.setHorizontalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(horariosPanelLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(GenerarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        horariosPanelLayout.setVerticalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, horariosPanelLayout.createSequentialGroup()
                .addContainerGap(235, Short.MAX_VALUE)
                .addComponent(GenerarHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(233, 233, 233))
        );

        jTabbedPane2.addTab("Horarios", horariosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroAulaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAulaButtonActionPerformed
        // TODO add your handling code here:
        int idAula = Integer.parseInt(capacidadRegistroAulaTextArea.getText());
        grafoPrincipal.agregarAula(idAula);
    }//GEN-LAST:event_registroAulaButtonActionPerformed

    private void GenerarHorariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarHorariosActionPerformed
        // TODO add your handling code here:
        ProgramadorHorarios.colorearAristas(grafoPrincipal);
        ProgramadorHorarios.imprimirHorario(grafoPrincipal);
    }//GEN-LAST:event_GenerarHorariosActionPerformed

    private void registrarProfesorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarProfesorButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarProfesorButtonActionPerformed

    private void eliminaraAulaButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaraAulaButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminaraAulaButton1ActionPerformed

    private void eliminaraAulaButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminaraAulaButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminaraAulaButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerarHorarios;
    private javax.swing.JButton agregarCursoProfesorButton;
    private javax.swing.JLabel asignarCursosLabel;
    private javax.swing.JPanel aulasPanel;
    private javax.swing.JLabel capacidadRegistroAulaLabel;
    private javax.swing.JLabel capacidadRegistroAulaLabel1;
    private javax.swing.JLabel capacidadRegistroAulaLabel2;
    private javax.swing.JTextField capacidadRegistroAulaTextArea;
    private javax.swing.JTextField capacidadRegistroAulaTextArea1;
    private javax.swing.JTextField capacidadRegistroAulaTextArea2;
    private javax.swing.JTextField codCursoTextArea;
    private javax.swing.JTextField codigoProfesorTextArea;
    private javax.swing.JTextField codigoProfesorTextArea1;
    private javax.swing.JLabel códigoProfesorLabel;
    private javax.swing.JLabel códigoProfesorLabel1;
    private javax.swing.JComboBox<String> datosAulasComboBox;
    private javax.swing.JComboBox<String> datosProfesoresComboBox;
    private javax.swing.JButton editarProfesorButton;
    private javax.swing.JButton editarProfesorButton1;
    private javax.swing.JButton eliminarProfesorButton;
    private javax.swing.JButton eliminaraAulaButton;
    private javax.swing.JButton eliminaraAulaButton1;
    private javax.swing.JButton eliminaraAulaButton2;
    private javax.swing.JButton eliminiarCursoProfesorButton;
    private javax.swing.JPanel horariosPanel;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel nombreAulaLabel;
    private javax.swing.JLabel nombreAulaLabel1;
    private javax.swing.JTextField nombreAulaTextArea;
    private javax.swing.JTextField nombreAulaTextArea1;
    private javax.swing.JLabel nombreProfesorLabel;
    private javax.swing.JLabel nombreProfesorLabel1;
    private javax.swing.JTextField nombreProfesorTextArea;
    private javax.swing.JTextField nombreProfesorTextArea1;
    private javax.swing.JLabel nombreRegistroAulaLabel;
    private javax.swing.JTextField nombreRegistroAulaTextArea;
    private javax.swing.JPanel profesoresPanel;
    private javax.swing.JLabel registrarAulaButton;
    private javax.swing.JButton registrarProfesorButton;
    private javax.swing.JButton registroAulaButton;
    // End of variables declaration//GEN-END:variables
}
