/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tf_pc;

/**
 *
 * @author Dayana
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        cursosPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JTabbedPane();
        bloquesPanel = new javax.swing.JPanel();
        ciclo1Label = new javax.swing.JLabel();
        ciclo2Label = new javax.swing.JLabel();
        ciclo3Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        adminCursosPanel = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        registrarLabel = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        creditosLabel = new javax.swing.JLabel();
        cicloLabel = new javax.swing.JLabel();
        clasesSemanalesLabel = new javax.swing.JLabel();
        registrarButton = new javax.swing.JButton();
        nombreTextField = new javax.swing.JTextField();
        creditosTextField = new javax.swing.JTextField();
        cicloComboBox = new javax.swing.JComboBox<>();
        clasesSemanalesComboBox = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        codigoLabel = new javax.swing.JLabel();
        nombreInfoLabel = new javax.swing.JLabel();
        creditosInfoLabel = new javax.swing.JLabel();
        cicloInfoLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        codigoTextField = new javax.swing.JTextField();
        nombreInfoTextField = new javax.swing.JTextField();
        creditosInfoTextField = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        profesoresPanel = new javax.swing.JPanel();
        datosProfesoresComboBox = new javax.swing.JComboBox<>();
        nombreProfesorLabel = new javax.swing.JLabel();
        códigoProfesorLabel = new javax.swing.JLabel();
        editarProfesorButton = new javax.swing.JButton();
        guardarProfesorButton = new javax.swing.JButton();
        eliminarProfesorButton = new javax.swing.JButton();
        asignarCursosLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        agregarCursoProfesorButton = new javax.swing.JButton();
        eliminiarCursoProfesorButton = new javax.swing.JButton();
        codCursoTextArea = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreRegistroProfesorTextArea = new javax.swing.JTextField();
        codigoRegistroProfesorTextArea = new javax.swing.JTextField();
        registrarProfesorButton = new javax.swing.JButton();
        horarioDisponiblesLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        nombreProfesorTextArea = new javax.swing.JTextField();
        codigoProfesorTextArea = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        modificarDíaComboBox = new javax.swing.JComboBox<>();
        modificarHorarioProfesorComboBox = new javax.swing.JComboBox<>();
        agregarHorarioModificadoButton = new javax.swing.JButton();
        quitarHorarioModificadoButton = new javax.swing.JButton();
        aulasPanel = new javax.swing.JPanel();
        datosAulasComboBox = new javax.swing.JComboBox<>();
        nombreAulaLabel = new javax.swing.JLabel();
        nombreAulaTextArea = new javax.swing.JTextField();
        capacidadAulaLabel = new javax.swing.JLabel();
        capacidadAulaTextArea = new javax.swing.JTextField();
        editarAulaButton = new javax.swing.JButton();
        guardarAulaButton = new javax.swing.JButton();
        eliminaraAulaButton = new javax.swing.JButton();
        registrarAulaButton = new javax.swing.JLabel();
        nombreRegistroAulaLabel = new javax.swing.JLabel();
        nombreRegistroAulaTextArea = new javax.swing.JTextField();
        capacidadRegistroAulaLabel = new javax.swing.JLabel();
        capacidadRegistroAulaTextArea = new javax.swing.JTextField();
        registroAulaButton = new javax.swing.JButton();
        jScrollPane13 = new javax.swing.JScrollPane();
        aulasTable = new javax.swing.JTable();
        horarioDisponibleAulaLabel = new javax.swing.JLabel();
        modificarHorarioAulaLabel = new javax.swing.JLabel();
        modificarDiaAulaComboBox = new javax.swing.JComboBox<>();
        modificarHoraAulaComboBox = new javax.swing.JComboBox<>();
        agregarAulaModificadaButton = new javax.swing.JButton();
        quitarAulaModificadaButton = new javax.swing.JButton();
        horariosPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ciclo1Label.setText("Ciclo 1");

        ciclo2Label.setText("Ciclo 2");

        ciclo3Label.setText("Ciclo 3");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea5.setEditable(false);
        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jScrollPane6.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane6.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea6.setEditable(false);
        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jScrollPane6.setViewportView(jTextArea6);

        jScrollPane7.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane7.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea7.setEditable(false);
        jTextArea7.setColumns(20);
        jTextArea7.setRows(5);
        jScrollPane7.setViewportView(jTextArea7);

        jScrollPane8.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane8.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea8.setEditable(false);
        jTextArea8.setColumns(20);
        jTextArea8.setRows(5);
        jScrollPane8.setViewportView(jTextArea8);

        jScrollPane9.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane9.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea9.setEditable(false);
        jTextArea9.setColumns(20);
        jTextArea9.setRows(5);
        jScrollPane9.setViewportView(jTextArea9);

        jScrollPane10.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane10.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea10.setEditable(false);
        jTextArea10.setColumns(20);
        jTextArea10.setRows(5);
        jScrollPane10.setViewportView(jTextArea10);

        javax.swing.GroupLayout bloquesPanelLayout = new javax.swing.GroupLayout(bloquesPanel);
        bloquesPanel.setLayout(bloquesPanelLayout);
        bloquesPanelLayout.setHorizontalGroup(
            bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloquesPanelLayout.createSequentialGroup()
                .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bloquesPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79)
                        .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(bloquesPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(ciclo1Label)
                        .addGap(195, 195, 195)
                        .addComponent(ciclo2Label)
                        .addGap(193, 193, 193)
                        .addComponent(ciclo3Label)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        bloquesPanelLayout.setVerticalGroup(
            bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bloquesPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciclo1Label)
                    .addComponent(ciclo2Label)
                    .addComponent(ciclo3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bloquesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        adminPanel.addTab("Bloques creados", bloquesPanel);

        infoLabel.setText("Información de cursos");

        registrarLabel.setText("Registrar cursos");

        nombreLabel.setText("Nombre");

        creditosLabel.setText("Creditos");

        cicloLabel.setText("Ciclo");

        clasesSemanalesLabel.setText("Clases a la semana");

        registrarButton.setText("Registrar");

        cicloComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        cicloComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cicloComboBoxActionPerformed(evt);
            }
        });

        clasesSemanalesComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        clasesSemanalesComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clasesSemanalesComboBoxActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        codigoLabel.setText("Código");

        nombreInfoLabel.setText("Nombre");

        creditosInfoLabel.setText("Créditos");

        cicloInfoLabel.setText("Ciclo");

        jLabel6.setText("Clases a la semana");

        editarButton.setText("Editar");

        guardarButton.setText("Guardar");

        eliminarButton.setText("Eliminar");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout adminCursosPanelLayout = new javax.swing.GroupLayout(adminCursosPanel);
        adminCursosPanel.setLayout(adminCursosPanelLayout);
        adminCursosPanelLayout.setHorizontalGroup(
            adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCursosPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarLabel)
                .addGap(168, 168, 168))
            .addGroup(adminCursosPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminCursosPanelLayout.createSequentialGroup()
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(510, 510, 510))
                    .addGroup(adminCursosPanelLayout.createSequentialGroup()
                        .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoLabel)
                            .addComponent(nombreInfoLabel)
                            .addComponent(creditosInfoLabel)
                            .addComponent(cicloInfoLabel)
                            .addComponent(jLabel6))
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(codigoTextField)
                                .addComponent(nombreInfoTextField)
                                .addComponent(creditosInfoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(129, 129, 129)
                        .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clasesSemanalesLabel)
                            .addComponent(cicloLabel)
                            .addComponent(creditosLabel)
                            .addComponent(nombreLabel))
                        .addGap(59, 59, 59)
                        .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(creditosTextField)
                            .addComponent(cicloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clasesSemanalesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74))
                    .addGroup(adminCursosPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(editarButton)
                        .addGap(58, 58, 58)
                        .addComponent(guardarButton)
                        .addGap(54, 54, 54)
                        .addComponent(eliminarButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminCursosPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registrarButton)
                .addGap(167, 167, 167))
        );
        adminCursosPanelLayout.setVerticalGroup(
            adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminCursosPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoLabel)
                    .addComponent(registrarLabel))
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoLabel)
                    .addComponent(codigoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditosLabel)
                    .addComponent(creditosTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreInfoLabel)
                    .addComponent(nombreInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cicloLabel)
                    .addComponent(cicloComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(creditosInfoLabel)
                    .addComponent(creditosInfoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cicloInfoLabel)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clasesSemanalesLabel)
                    .addComponent(clasesSemanalesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(registrarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(adminCursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarButton)
                    .addComponent(guardarButton)
                    .addComponent(eliminarButton))
                .addGap(50, 50, 50))
        );

        infoLabel.getAccessibleContext().setAccessibleName("Label1");

        adminPanel.addTab("Administrar cursos", adminCursosPanel);

        javax.swing.GroupLayout cursosPanelLayout = new javax.swing.GroupLayout(cursosPanel);
        cursosPanel.setLayout(cursosPanelLayout);
        cursosPanelLayout.setHorizontalGroup(
            cursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel))
        );
        cursosPanelLayout.setVerticalGroup(
            cursosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cursosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(adminPanel))
        );

        adminPanel.getAccessibleContext().setAccessibleName("admin panel");

        jTabbedPane2.addTab("Cursos", cursosPanel);

        datosProfesoresComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prof 1", "Prof 2", "Prof 3", "Prof 4" }));

        nombreProfesorLabel.setText("Nombre");

        códigoProfesorLabel.setText("Código");

        editarProfesorButton.setText("Editar");

        guardarProfesorButton.setText("Guardar");

        eliminarProfesorButton.setText("Eliminar");

        asignarCursosLabel.setText("Asignar cursos al profesor");

        jLabel4.setText("Codigo curso");

        agregarCursoProfesorButton.setText("Agregar");

        eliminiarCursoProfesorButton.setText("Eliminar");

        jLabel5.setText("Registrar Profesor");

        jLabel7.setText("Nombre");

        jLabel8.setText("Código");

        registrarProfesorButton.setText("Registrar");

        horarioDisponiblesLabel.setText("Horario de disponibilidad de profesor");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel10.setText("Capacitado para dar los cursos");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane12.setViewportView(jTextArea2);

        jLabel11.setText("Modificar horario de disponibilidad del profesor");

        modificarDíaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dia", "Lunes", "Martes", "Miercoles", "Viernes", "Sabado" }));

        modificarHorarioProfesorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Horario", "Horario 1", "Horario 2", "Horario 3" }));

        agregarHorarioModificadoButton.setText("Agregar");

        quitarHorarioModificadoButton.setText("Quitar");
        quitarHorarioModificadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarHorarioModificadoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profesoresPanelLayout = new javax.swing.GroupLayout(profesoresPanel);
        profesoresPanel.setLayout(profesoresPanelLayout);
        profesoresPanelLayout.setHorizontalGroup(
            profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresPanelLayout.createSequentialGroup()
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(agregarCursoProfesorButton)
                                .addGap(26, 26, 26)
                                .addComponent(eliminiarCursoProfesorButton))
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codCursoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(asignarCursosLabel)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addComponent(editarProfesorButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guardarProfesorButton)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarProfesorButton))
                            .addComponent(datosProfesoresComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreProfesorLabel)
                                    .addComponent(códigoProfesorLabel))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreProfesorTextArea)
                                    .addComponent(codigoProfesorTextArea)))
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigoRegistroProfesorTextArea)
                                    .addComponent(nombreRegistroProfesorTextArea)))))
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(registrarProfesorButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profesoresPanelLayout.createSequentialGroup()
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(profesoresPanelLayout.createSequentialGroup()
                                .addComponent(modificarDíaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(modificarHorarioProfesorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(agregarHorarioModificadoButton)
                                .addGap(18, 18, 18)
                                .addComponent(quitarHorarioModificadoButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(profesoresPanelLayout.createSequentialGroup()
                        .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(horarioDisponiblesLabel))
                        .addContainerGap())))
        );
        profesoresPanelLayout.setVerticalGroup(
            profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profesoresPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(datosProfesoresComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreProfesorLabel)
                    .addComponent(nombreProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(códigoProfesorLabel)
                    .addComponent(codigoProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarProfesorButton)
                    .addComponent(guardarProfesorButton)
                    .addComponent(eliminarProfesorButton))
                .addGap(28, 28, 28)
                .addComponent(asignarCursosLabel)
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(codCursoTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCursoProfesorButton)
                    .addComponent(eliminiarCursoProfesorButton))
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nombreRegistroProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(codigoRegistroProfesorTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(registrarProfesorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(profesoresPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(horarioDisponiblesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(profesoresPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modificarDíaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarHorarioProfesorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarHorarioModificadoButton)
                    .addComponent(quitarHorarioModificadoButton))
                .addGap(43, 43, 43))
        );

        jTabbedPane2.addTab("Profesores", profesoresPanel);

        datosAulasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        nombreAulaLabel.setText("Nombre");

        capacidadAulaLabel.setText("Capacidad");

        editarAulaButton.setText("Editar");

        guardarAulaButton.setText("Guardar");

        eliminaraAulaButton.setText("Eliminar");

        registrarAulaButton.setText("Registrar Aula");

        nombreRegistroAulaLabel.setText("Nombre");

        capacidadRegistroAulaLabel.setText("Capacidad");

        registroAulaButton.setText("Registrar");

        aulasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Hora", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"
            }
        ));
        jScrollPane13.setViewportView(aulasTable);

        horarioDisponibleAulaLabel.setText("Horario de disponbibilidad del aula");

        modificarHorarioAulaLabel.setText("Modificar el horario de disponibilidad del aula");

        modificarDiaAulaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        modificarHoraAulaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agregarAulaModificadaButton.setText("Agregar");

        quitarAulaModificadaButton.setText("Quitar");

        javax.swing.GroupLayout aulasPanelLayout = new javax.swing.GroupLayout(aulasPanel);
        aulasPanel.setLayout(aulasPanelLayout);
        aulasPanelLayout.setHorizontalGroup(
            aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aulasPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(registroAulaButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(aulasPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(registrarAulaButton)
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addComponent(editarAulaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(guardarAulaButton)
                        .addGap(34, 34, 34)
                        .addComponent(eliminaraAulaButton))
                    .addComponent(datosAulasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreAulaLabel)
                            .addComponent(capacidadAulaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(capacidadAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreAulaTextArea)))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreRegistroAulaLabel)
                            .addComponent(capacidadRegistroAulaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aulasPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarHorarioAulaLabel)
                            .addGroup(aulasPanelLayout.createSequentialGroup()
                                .addComponent(modificarDiaAulaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(modificarHoraAulaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(agregarAulaModificadaButton)
                                .addGap(18, 18, 18)
                                .addComponent(quitarAulaModificadaButton))
                            .addComponent(horarioDisponibleAulaLabel))
                        .addContainerGap())))
        );
        aulasPanelLayout.setVerticalGroup(
            aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aulasPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(datosAulasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horarioDisponibleAulaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(aulasPanelLayout.createSequentialGroup()
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreAulaLabel)
                            .addComponent(nombreAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidadAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(capacidadAulaLabel))
                        .addGap(38, 38, 38)
                        .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editarAulaButton)
                            .addComponent(guardarAulaButton)
                            .addComponent(eliminaraAulaButton)))
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarAulaButton)
                    .addComponent(modificarHorarioAulaLabel))
                .addGap(18, 18, 18)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreRegistroAulaLabel)
                    .addComponent(nombreRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarDiaAulaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarHoraAulaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarAulaModificadaButton)
                    .addComponent(quitarAulaModificadaButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(aulasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capacidadRegistroAulaLabel)
                    .addComponent(capacidadRegistroAulaTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(registroAulaButton)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Aulas", aulasPanel);

        javax.swing.GroupLayout horariosPanelLayout = new javax.swing.GroupLayout(horariosPanel);
        horariosPanel.setLayout(horariosPanelLayout);
        horariosPanelLayout.setHorizontalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );
        horariosPanelLayout.setVerticalGroup(
            horariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 482, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Horarios", horariosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void clasesSemanalesComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clasesSemanalesComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clasesSemanalesComboBoxActionPerformed

    private void cicloComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cicloComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cicloComboBoxActionPerformed

    private void quitarHorarioModificadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarHorarioModificadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitarHorarioModificadoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminCursosPanel;
    private javax.swing.JTabbedPane adminPanel;
    private javax.swing.JButton agregarAulaModificadaButton;
    private javax.swing.JButton agregarCursoProfesorButton;
    private javax.swing.JButton agregarHorarioModificadoButton;
    private javax.swing.JLabel asignarCursosLabel;
    private javax.swing.JPanel aulasPanel;
    private javax.swing.JTable aulasTable;
    private javax.swing.JPanel bloquesPanel;
    private javax.swing.JLabel capacidadAulaLabel;
    private javax.swing.JTextField capacidadAulaTextArea;
    private javax.swing.JLabel capacidadRegistroAulaLabel;
    private javax.swing.JTextField capacidadRegistroAulaTextArea;
    private javax.swing.JLabel ciclo1Label;
    private javax.swing.JLabel ciclo2Label;
    private javax.swing.JLabel ciclo3Label;
    private javax.swing.JComboBox<String> cicloComboBox;
    private javax.swing.JLabel cicloInfoLabel;
    private javax.swing.JLabel cicloLabel;
    private javax.swing.JComboBox<String> clasesSemanalesComboBox;
    private javax.swing.JLabel clasesSemanalesLabel;
    private javax.swing.JTextField codCursoTextArea;
    private javax.swing.JLabel codigoLabel;
    private javax.swing.JTextField codigoProfesorTextArea;
    private javax.swing.JTextField codigoRegistroProfesorTextArea;
    private javax.swing.JTextField codigoTextField;
    private javax.swing.JLabel creditosInfoLabel;
    private javax.swing.JTextField creditosInfoTextField;
    private javax.swing.JLabel creditosLabel;
    private javax.swing.JTextField creditosTextField;
    private javax.swing.JPanel cursosPanel;
    private javax.swing.JLabel códigoProfesorLabel;
    private javax.swing.JComboBox<String> datosAulasComboBox;
    private javax.swing.JComboBox<String> datosProfesoresComboBox;
    private javax.swing.JButton editarAulaButton;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton editarProfesorButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JButton eliminarProfesorButton;
    private javax.swing.JButton eliminaraAulaButton;
    private javax.swing.JButton eliminiarCursoProfesorButton;
    private javax.swing.JButton guardarAulaButton;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton guardarProfesorButton;
    private javax.swing.JLabel horarioDisponibleAulaLabel;
    private javax.swing.JLabel horarioDisponiblesLabel;
    private javax.swing.JPanel horariosPanel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JComboBox<String> modificarDiaAulaComboBox;
    private javax.swing.JComboBox<String> modificarDíaComboBox;
    private javax.swing.JComboBox<String> modificarHoraAulaComboBox;
    private javax.swing.JLabel modificarHorarioAulaLabel;
    private javax.swing.JComboBox<String> modificarHorarioProfesorComboBox;
    private javax.swing.JLabel nombreAulaLabel;
    private javax.swing.JTextField nombreAulaTextArea;
    private javax.swing.JLabel nombreInfoLabel;
    private javax.swing.JTextField nombreInfoTextField;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreProfesorLabel;
    private javax.swing.JTextField nombreProfesorTextArea;
    private javax.swing.JLabel nombreRegistroAulaLabel;
    private javax.swing.JTextField nombreRegistroAulaTextArea;
    private javax.swing.JTextField nombreRegistroProfesorTextArea;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JPanel profesoresPanel;
    private javax.swing.JButton quitarAulaModificadaButton;
    private javax.swing.JButton quitarHorarioModificadoButton;
    private javax.swing.JLabel registrarAulaButton;
    private javax.swing.JButton registrarButton;
    private javax.swing.JLabel registrarLabel;
    private javax.swing.JButton registrarProfesorButton;
    private javax.swing.JButton registroAulaButton;
    // End of variables declaration//GEN-END:variables
}
